baseURL = "https://osmin625.github.io"
title = "OMIN"
theme = "gokarna"
languageCode = "ko"
defaultContentLanguage = "ko"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  footer = "OMIN"
  description = "ML Engineer, Data Science"
  avatarURL = "/images/from_scratch.webp"
  AvatarAltText = "OMIN"
  avatarSize = "size-m"
  showPostsOnHomePage = "recent"
  mathjax = true
  ShowTableOfContents = true
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = ""
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/%EC%8A%B9%EB%AF%BC-%EC%98%A4-406733230/"},
    {name = "email", url = "mailto:tmdals179@naver.com"},
    {name = "github", url = "https://github.com/osmin625"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    pre = "<span data-feather='list'></span>"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 3
  
  [[menu.main]]
    name = "archive"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4

  
  
  
  
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
